name: Build MKDocs And Publish To Github Pages

on:
  push:
    branches:
      - master
  # Allow manually running in the actions tab
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main from GitHub
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocstrings mkdocs-with-pdf mdx_gh_links mkdocs-pdf-export-plugin mkdocstrings-python mkdocs-video mkdocs-redirects mkdocs-enumerate-headings-plugin mkdocs-git-revision-date-localized-plugin shortuuid black

      - name: Ensure read and write permissions for docs directory
        run: |
          chmod -R 777 docs  # Grant full read/write permissions to all files and directories inside docs

      - name: Ensure read and write permissions for site directory
        run: |
          chmod -R 777 docs/site  # Grant full read/write permissions to all files and directories inside docs/site

      - name: Check the contents of docs directory
        run: |
          ls -R docs  # List all files and directories inside docs to ensure they exist

      - name: Create Mkdocs Config 🚀
        working-directory: ./docs
        run: ./create-mkdocs-html-config.sh  # Ensure this script exists and is executable

      - name: Build MkDocs site
        run: |
          mkdocs build --config-file docs/mkdocs.yml  # Build the MkDocs site
          echo "Site files after build:"
          ls -R docs/site  # List contents of docs/site after build

      - name: List contents of the site directory
        run: |
          ls -R docs/site  # Ensure the build generated files in the 'docs/site' folder

      - name: Deploy docs to GitHub Pages
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        with:
          folder: docs/site  # Make sure you're deploying the generated 'docs/site' folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml
