name: Build MKDocs And Publish To Github Pages

on:
  push:
    branches:
      - master
  # Allow manually running in the actions tab
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main from GitHub
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt  # Ensure this file is in the correct location

      - name: Ensure read and write permissions for docs directory
        run: |
          chmod -R +rw docs  # Grant read and write permissions to all files and directories inside docs

      - name: Check the contents of docs directory
        run: |
          ls -R docs  # List all files and directories inside docs to ensure they exist

      - name: Create Mkdocs Config 🚀
        working-directory: ./docs
        run: ./create-mkdocs-html-config.sh  # Ensure this script exists and is executable

      - name: Build MkDocs site
        run: |
          mkdocs build --config-file docs/mkdocs.yml  # Build the MkDocs site
          ls -R docs/site  # List contents of the site directory after build to check if it's created

      - name: List contents of the site directory
        run: ls -R docs/site  # Ensure the build generated files in the 'docs/site' folder

      - name: Deploy docs to GitHub Pages
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        with:
          folder: docs/site  # Make sure you're deploying the generated 'docs/site' folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml
