name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master  # Ensure this matches your branch name

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4  # Fixed name
        
      - name: Create MkDocs Config 🚀
        working-directory: ./docs
        run: ./create-mkdocs-html-config.sh  # Ensure this script exists and is executable

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml  # Fixed path
          EXTRA_PACKAGES: build-base
