name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master  # Ensure this matches your branch name
  workflow_dispatch:  # Allows manual runs from Actions tab

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material mkdocs-video qrcode

      - name: Verify MkDocs installation
        run: mkdocs --version  # Debugging step

      - name: Create MkDocs Config 🚀
        working-directory: ./docs
        run: ./create-mkdocs-html-config.sh  # Ensure this script exists

      - name: Build MkDocs Site
        run: mkdocs build --config-file docs/mkdocs.yml  # Adjust path if needed

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml
          EXTRA_PACKAGES: build-base
